# Generated by Django 4.0.3 on 2022-04-26 22:16

import ShareTheWorld.validators.validators
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='STWUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator('^[A-Za-z0-9_]*$', message='Ensure this value contains only letters, numbers, and underscore.')])),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3), ShareTheWorld.validators.validators.validate_only_letters])),
                ('last_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(3), ShareTheWorld.validators.validators.validate_only_letters])),
                ('date_of_birth', models.DateField(validators=[ShareTheWorld.validators.validators.MinDateValidator(datetime.date(1950, 1, 1)), ShareTheWorld.validators.validators.MaxDateValidator(datetime.date(2022, 4, 27))])),
                ('description', models.TextField()),
                ('picture', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
